FROM node:19-alpine

WORKDIR /app

COPY package.json ./

COPY prisma ./

COPY .env ./

COPY tsconfig.json ./

COPY . ./

RUN NODE_ENV=development npm install

RUN npx prisma generate --schema ./prisma/schema.prisma

RUN npx tsc

EXPOSE 3000

CMD ["npm", "run", "dev"]
