FROM node:alpine

WORKDIR /app

COPY package*.json ./

COPY .env ./

COPY tsconfig.json ./

RUN npm install

RUN npx prisma init --datasource-provider sqlite

COPY schema.prisma ./prisma

COPY . ./

RUN npx tsc

EXPOSE 3000

CMD ["npm", "run", "dev"]